//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/PlayerControls01.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls01: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls01()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls01"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""20543023-0cee-49e5-b111-fe46a2c46914"",
            ""actions"": [
                {
                    ""name"": ""p1Movement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""7270afc8-c9a9-4726-9af1-ddbee4062830"",
                    ""expectedControlType"": ""Stick"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""p1Skill"",
                    ""type"": ""Button"",
                    ""id"": ""a4761551-1e18-4b87-b218-9065e5eab14d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""p1HeadMovement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""906e6b80-0605-4186-89e5-a26706731980"",
                    ""expectedControlType"": ""Stick"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""1eeb6c41-ff15-448a-b452-003eee45b72a"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""p1Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""934be5ec-2322-470f-a41c-84c790c4c9ad"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""p1Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""69bb02ad-88b0-45fd-9106-ed00faf4a048"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""p1Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""4b1850c8-d685-4965-a3f7-fc39d1623f44"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""p1Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""2223b056-a516-45be-bdd8-9a129edfd534"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""p1Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""436eafc9-ed94-4602-a986-afb8f9530bcf"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""p1Skill"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""d31c8b77-74da-4dbf-b90a-cf9d7af5a92d"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""p1HeadMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""3e688c49-4a5c-4fe7-8e7f-26fa90837ef3"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""p1HeadMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""9246ce1b-2db2-4f71-84d3-291e78e1ce41"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""p1HeadMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""99b2aa53-e7fc-43d3-8fe2-cf684cff7a50"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""p1HeadMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""59f66cbf-e8ac-4c55-a169-c97533c15ca1"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""p1HeadMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""Select"",
            ""id"": ""268cff76-c20a-43f4-82a0-1c115a3fde36"",
            ""actions"": [
                {
                    ""name"": ""p1Decide"",
                    ""type"": ""Button"",
                    ""id"": ""ae82efea-f906-4e34-8e1d-50cc121966c1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""p1CursorMove"",
                    ""type"": ""PassThrough"",
                    ""id"": ""1cc3395f-f960-418a-948b-0e55eb5b72d6"",
                    ""expectedControlType"": ""Stick"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8e2907a3-8f80-4f1a-b5df-25ea46721d8d"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""p1Decide"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""dafbf003-3713-44d0-826b-1447b64b7524"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""p1CursorMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""8b338003-471f-4e3c-ac1c-db75e8895c03"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""p1CursorMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""982ccb78-b37f-4488-93ff-c5f5fbd6d234"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""p1CursorMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""1128de6e-a5c4-4c50-9efd-b962303729ff"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""p1CursorMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""f3918f26-2aa3-4f3a-9ec3-95b804cee386"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""p1CursorMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Controller"",
            ""bindingGroup"": ""Controller"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Gameplay
        m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
        m_Gameplay_p1Movement = m_Gameplay.FindAction("p1Movement", throwIfNotFound: true);
        m_Gameplay_p1Skill = m_Gameplay.FindAction("p1Skill", throwIfNotFound: true);
        m_Gameplay_p1HeadMovement = m_Gameplay.FindAction("p1HeadMovement", throwIfNotFound: true);
        // Select
        m_Select = asset.FindActionMap("Select", throwIfNotFound: true);
        m_Select_p1Decide = m_Select.FindAction("p1Decide", throwIfNotFound: true);
        m_Select_p1CursorMove = m_Select.FindAction("p1CursorMove", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Gameplay
    private readonly InputActionMap m_Gameplay;
    private List<IGameplayActions> m_GameplayActionsCallbackInterfaces = new List<IGameplayActions>();
    private readonly InputAction m_Gameplay_p1Movement;
    private readonly InputAction m_Gameplay_p1Skill;
    private readonly InputAction m_Gameplay_p1HeadMovement;
    public struct GameplayActions
    {
        private @PlayerControls01 m_Wrapper;
        public GameplayActions(@PlayerControls01 wrapper) { m_Wrapper = wrapper; }
        public InputAction @p1Movement => m_Wrapper.m_Gameplay_p1Movement;
        public InputAction @p1Skill => m_Wrapper.m_Gameplay_p1Skill;
        public InputAction @p1HeadMovement => m_Wrapper.m_Gameplay_p1HeadMovement;
        public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        public void AddCallbacks(IGameplayActions instance)
        {
            if (instance == null || m_Wrapper.m_GameplayActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Add(instance);
            @p1Movement.started += instance.OnP1Movement;
            @p1Movement.performed += instance.OnP1Movement;
            @p1Movement.canceled += instance.OnP1Movement;
            @p1Skill.started += instance.OnP1Skill;
            @p1Skill.performed += instance.OnP1Skill;
            @p1Skill.canceled += instance.OnP1Skill;
            @p1HeadMovement.started += instance.OnP1HeadMovement;
            @p1HeadMovement.performed += instance.OnP1HeadMovement;
            @p1HeadMovement.canceled += instance.OnP1HeadMovement;
        }

        private void UnregisterCallbacks(IGameplayActions instance)
        {
            @p1Movement.started -= instance.OnP1Movement;
            @p1Movement.performed -= instance.OnP1Movement;
            @p1Movement.canceled -= instance.OnP1Movement;
            @p1Skill.started -= instance.OnP1Skill;
            @p1Skill.performed -= instance.OnP1Skill;
            @p1Skill.canceled -= instance.OnP1Skill;
            @p1HeadMovement.started -= instance.OnP1HeadMovement;
            @p1HeadMovement.performed -= instance.OnP1HeadMovement;
            @p1HeadMovement.canceled -= instance.OnP1HeadMovement;
        }

        public void RemoveCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGameplayActions instance)
        {
            foreach (var item in m_Wrapper.m_GameplayActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GameplayActions @Gameplay => new GameplayActions(this);

    // Select
    private readonly InputActionMap m_Select;
    private List<ISelectActions> m_SelectActionsCallbackInterfaces = new List<ISelectActions>();
    private readonly InputAction m_Select_p1Decide;
    private readonly InputAction m_Select_p1CursorMove;
    public struct SelectActions
    {
        private @PlayerControls01 m_Wrapper;
        public SelectActions(@PlayerControls01 wrapper) { m_Wrapper = wrapper; }
        public InputAction @p1Decide => m_Wrapper.m_Select_p1Decide;
        public InputAction @p1CursorMove => m_Wrapper.m_Select_p1CursorMove;
        public InputActionMap Get() { return m_Wrapper.m_Select; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SelectActions set) { return set.Get(); }
        public void AddCallbacks(ISelectActions instance)
        {
            if (instance == null || m_Wrapper.m_SelectActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_SelectActionsCallbackInterfaces.Add(instance);
            @p1Decide.started += instance.OnP1Decide;
            @p1Decide.performed += instance.OnP1Decide;
            @p1Decide.canceled += instance.OnP1Decide;
            @p1CursorMove.started += instance.OnP1CursorMove;
            @p1CursorMove.performed += instance.OnP1CursorMove;
            @p1CursorMove.canceled += instance.OnP1CursorMove;
        }

        private void UnregisterCallbacks(ISelectActions instance)
        {
            @p1Decide.started -= instance.OnP1Decide;
            @p1Decide.performed -= instance.OnP1Decide;
            @p1Decide.canceled -= instance.OnP1Decide;
            @p1CursorMove.started -= instance.OnP1CursorMove;
            @p1CursorMove.performed -= instance.OnP1CursorMove;
            @p1CursorMove.canceled -= instance.OnP1CursorMove;
        }

        public void RemoveCallbacks(ISelectActions instance)
        {
            if (m_Wrapper.m_SelectActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ISelectActions instance)
        {
            foreach (var item in m_Wrapper.m_SelectActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_SelectActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public SelectActions @Select => new SelectActions(this);
    private int m_ControllerSchemeIndex = -1;
    public InputControlScheme ControllerScheme
    {
        get
        {
            if (m_ControllerSchemeIndex == -1) m_ControllerSchemeIndex = asset.FindControlSchemeIndex("Controller");
            return asset.controlSchemes[m_ControllerSchemeIndex];
        }
    }
    public interface IGameplayActions
    {
        void OnP1Movement(InputAction.CallbackContext context);
        void OnP1Skill(InputAction.CallbackContext context);
        void OnP1HeadMovement(InputAction.CallbackContext context);
    }
    public interface ISelectActions
    {
        void OnP1Decide(InputAction.CallbackContext context);
        void OnP1CursorMove(InputAction.CallbackContext context);
    }
}
